# Generated by Django 4.2.14 on 2025-10-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RankingSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking_type', models.CharField(choices=[('like', '点赞榜'), ('point', '积分榜'), ('combined', '综合榜')], max_length=10)),
                ('snapshot_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '排行榜快照',
                'verbose_name_plural': '排行榜快照',
                'ordering': ['-created_at'],
            },
        ),
    ]
