# Generated by Django 4.2.14 on 2025-10-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ranking', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='rankingsnapshot',
            index=models.Index(fields=['ranking_type', '-created_at'], name='Ranking_ran_ranking_a12398_idx'),
        ),
        migrations.AddIndex(
            model_name='rankingsnapshot',
            index=models.Index(fields=['-created_at'], name='Ranking_ran_created_15cb36_idx'),
        ),
    ]
