# Generated by Django 4.2.14 on 2024-08-05 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('content', models.CharField(max_length=800)),
                ('board_date', models.DateField()),
                ('like_point', models.IntegerField(default=0)),
                ('image_path', models.CharField(blank=True, default='', max_length=100)),
                ('type', models.IntegerField()),
            ],
        ),
    ]
