# Generated by Django 4.2.14 on 2024-08-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardManagement', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Message',
            new_name='BoradInfo',
        ),
    ]
