# Generated by Django 4.2.14 on 2024-10-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardManagement', '0003_alter_boradinfo_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='boradinfo',
            name='dontlike_point',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boradinfo',
            name='board_date',
            field=models.DateTimeField(),
        ),
    ]
