# Generated by Django 4.2.14 on 2025-10-13 05:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BoardManagement', '0004_boradinfo_dontlike_point_alter_boradinfo_board_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoradInfo',
            new_name='BoardInfo',
        ),
    ]
