# Generated by Django 4.2.14 on 2025-10-16 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardManagement', '0005_rename_boradinfo_boardinfo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boardinfo',
            name='board_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='boardinfo',
            name='image_path',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
