# Generated by Django 4.2.14 on 2025-10-16 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BoardManagement', '0006_alter_boardinfo_board_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boardinfo',
            options={'ordering': ['-board_date']},
        ),
        migrations.AddField(
            model_name='boardinfo',
            name='user',
            field=models.ForeignKey(blank=True, help_text='关联用户（新增功能）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='boards', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='boardinfo',
            name='content',
            field=models.TextField(verbose_name='留言内容'),
        ),
        migrations.AlterField(
            model_name='boardinfo',
            name='username',
            field=models.CharField(db_index=True, help_text='留言用户名（兼容历史数据）', max_length=20),
        ),
        migrations.AddIndex(
            model_name='boardinfo',
            index=models.Index(fields=['username', 'board_date'], name='BoardManage_usernam_6222aa_idx'),
        ),
    ]
