# Generated by Django 4.2.14 on 2025-10-17 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardManagement', '0007_alter_boardinfo_options_boardinfo_user_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boardinfo',
            index=models.Index(fields=['-board_date'], name='BoardManage_board_d_2b0783_idx'),
        ),
        migrations.AddIndex(
            model_name='boardinfo',
            index=models.Index(fields=['board_date'], name='BoardManage_board_d_fdfabc_idx'),
        ),
        migrations.AddIndex(
            model_name='boardinfo',
            index=models.Index(fields=['-like_point', '-board_date'], name='BoardManage_like_po_7aefc3_idx'),
        ),
        migrations.AddIndex(
            model_name='boardinfo',
            index=models.Index(fields=['like_point', '-board_date'], name='BoardManage_like_po_c3e694_idx'),
        ),
    ]
