# Generated by Django 4.2.14 on 2025-10-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardManagement', '0008_boardinfo_boardmanage_board_d_2b0783_idx_and_more'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boardinfo',
            index=models.Index(fields=['user', '-board_date'], name='BoardManage_user_id_b953b4_idx'),
        ),
    ]
