# Generated by Django 4.2.14 on 2025-10-23 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BoardManagement', '0009_boardinfo_boardmanage_user_id_b953b4_idx'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='boardinfo',
            index=models.Index(fields=['username', '-board_date'], name='BoardManage_usernam_5552df_idx'),
        ),
    ]
