"""
Django settings for yyxbbs project.

Generated by 'django-admin startproject' using Django 4.2.14.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-@!m$i_otf6e(cb$+1=&#kwyzgqe=oqw732y&ylerm)(xju39uq'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

# 服务器专属设置↓
ALLOWED_HOSTS = [
    'frp-all.com',      # 如果需要支持不带 www 的域名
    'localhost',       # 本地开发环境
    '127.0.0.1',       # 本地开发环境
    'win-k0k4u5uuhl2',
    'frp-all.com',      # 樱花隧道
    'www.yyxbbs.cn',
    'yyxbbs.cn'
]
CSRF_TRUSTED_ORIGINS = [
    'https://frp-all.com:13491',
    'https://www.frp-all.com',
    'https://frp-all.com'  # 如果需要支持不带 www 的域名
]
# 服务器专属设置↑

# Application definition

# 这里要注册app
INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'debug_toolbar',

    'Userlogin.apps.UserloginConfig',
    'BoardManagement.apps.BoardmanagementConfig',
    'DailyAttendance.apps.DailyattendanceConfig',
    'DeepSeek.apps.DeepseekConfig'

]

MIDDLEWARE = [
    'debug_toolbar.middleware.DebugToolbarMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'yyxbbs.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'yyxbbs.wsgi.application'

DEBUG_TOOLBAR_CONFIG = {
    'SHOW_TOOLBAR_CALLBACK': lambda request: True,  # 总是显示工具栏
    'RESULTS_CACHE_SIZE': 100,  # 缓存结果数量
    'SHOW_COLLAPSED': True,     # 显示折叠的工具栏
    'PROFILER_MAX_DEPTH': 10,   # 分析器最大深度
}

# 配置内部IPs
INTERNAL_IPS = [
    '127.0.0.1',
    'localhost',
]

# 如果需要，配置Debug Toolbar的面板
DEBUG_TOOLBAR_PANELS = [
    'debug_toolbar.panels.history.HistoryPanel',
    'debug_toolbar.panels.versions.VersionsPanel',
    'debug_toolbar.panels.timer.TimerPanel',
    'debug_toolbar.panels.settings.SettingsPanel',
    'debug_toolbar.panels.headers.HeadersPanel',
    'debug_toolbar.panels.request.RequestPanel',
    'debug_toolbar.panels.sql.SQLPanel',
    'debug_toolbar.panels.staticfiles.StaticFilesPanel',
    'debug_toolbar.panels.templates.TemplatesPanel',
    'debug_toolbar.panels.cache.CachePanel',
    'debug_toolbar.panels.signals.SignalsPanel',
    'debug_toolbar.panels.logging.LoggingPanel',
    'debug_toolbar.panels.redirects.RedirectsPanel',
    'debug_toolbar.panels.profiling.ProfilingPanel',
]

# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.sqlite3',
#         'NAME': BASE_DIR / 'db.sqlite3',
#     }
# }
#这里数据库换成mysql的
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'db',
        'USER':'root',
        'PASSWORD':'WANG892207142.',
        'HOST':'127.0.0.1',
        'PORT': 3306,
        'OPTIONS': {
            'charset': 'utf8mb4',
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'connect_timeout': 10,
        },
        #'CONN_MAX_AGE': 300,  # 连接保持时间（秒）
        'CONN_HEALTH_CHECKS': True,
    }
}

# Redis 缓存配置
CACHES = {
    "default": {
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/1",  # 使用1号数据库，避免与其它数据混用
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 100,  # 连接池大小
                "retry_on_timeout": True,
            },
            "SOCKET_CONNECT_TIMEOUT": 5,  # 连接超时（秒）
            "SOCKET_TIMEOUT": 5,  # 读写超时（秒）
            "COMPRESSOR": "django_redis.compressors.zlib.ZlibCompressor",  # 压缩存储
            "IGNORE_EXCEPTIONS": True,  # Redis异常时不抛错，直接回退到数据库
        },
        "KEY_PREFIX": "yyxbbs",  # 缓存键前缀
    },
    "session": {  # 专门用于Session的Redis配置
        "BACKEND": "django_redis.cache.RedisCache",
        "LOCATION": "redis://127.0.0.1:6379/2",  # 使用2号数据库专门存储Session
        "OPTIONS": {
            "CLIENT_CLASS": "django_redis.client.DefaultClient",
            "CONNECTION_POOL_KWARGS": {
                "max_connections": 50,
            },
            "SOCKET_CONNECT_TIMEOUT": 5,
            "SOCKET_TIMEOUT": 5,
        },
        "KEY_PREFIX": "yyxbbs_session",
    }
}

# Session 配置 - 使用 Redis 存储
SESSION_ENGINE = "django.contrib.sessions.backends.cache"
SESSION_CACHE_ALIAS = "session"  # 使用上面配置的session缓存
SESSION_COOKIE_AGE = 3600 #(1h) #1209600  # Session过期时间（2周，单位：秒）
SESSION_EXPIRE_AT_BROWSER_CLOSE = False  # 浏览器关闭时不过期
SESSION_SAVE_EVERY_REQUEST = True  # 每次请求都保存Session，延长过期时间

# 安全相关配置
SESSION_COOKIE_SECURE = False  # 本地开发设为False，生产环境应设为True（HTTPS）
SESSION_COOKIE_HTTPONLY = True  # 防止XSS读取Session
SESSION_COOKIE_SAMESITE = 'Lax'  # CSRF保护

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# 认证设置，用于持久化用户信息
AUTH_USER_MODEL = 'Userlogin.UserInfo'




# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#bootstrap路径
STATIC_URL = '/static/'
STATICFILES_DIRS = ( os.path.join('static'), )
STATIC_ROOT = ''

# DeepSeek相关
DEEPSEEK_API_KEY = "sk-e0894fd69b924b6f9fc4d501ca360f6b"
DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions"
# DEEPSEEK_API_URL = "https://api.deepseek.com/v1/chat/completions"  # 确认API端点

TIME_ZONE = 'Asia/Shanghai'