# Generated by Django 4.2.14 on 2025-02-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userlogin', '0002_remove_userinfo_login_data_userinfo_groups_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='last_attendance_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
