# Generated by Django 4.2.14 on 2025-10-13 13:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userlogin', '0003_userinfo_last_attendance_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BoradInfo',
            new_name='BoardInfo',
        ),
    ]
