# Generated by Django 4.2.14 on 2025-10-16 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Userlogin', '0004_rename_boradinfo_boardinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BoardInfo',
        ),
    ]
