# Generated by Django 4.2.14 on 2025-10-22 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userlogin', '0005_delete_boardinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='total_likes',
            field=models.IntegerField(default=0),
        ),
    ]
