# Generated by Django 4.2.14 on 2025-10-22 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Userlogin', '0006_userinfo_total_likes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['-total_likes', '-point'], name='Userlogin_u_total_l_c11e0e_idx'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['-total_likes'], name='Userlogin_u_total_l_3ba01b_idx'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['-point'], name='Userlogin_u_point_0ff222_idx'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['is_active', '-total_likes'], name='Userlogin_u_is_acti_fe28b8_idx'),
        ),
        migrations.AddIndex(
            model_name='userinfo',
            index=models.Index(fields=['is_active', '-point'], name='Userlogin_u_is_acti_854184_idx'),
        ),
    ]
